version: '3'
services:
  web_client:
    # build: ./client
    image: samsonmaconi/finn.ai-challenge-client
    ports:
     - "8888:8888"
    links:
     - web_server
  web_server:
    # build: ./server
    image: samsonmaconi/finn.ai-challenge-server
    ports:
    - "3000:3000"