# Use node 11.10.1 LTS
FROM node:11.10.1

COPY . /app

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PORT_EXPRESS_SRV=3000
ENV PORT_FLASK_SRV=5000
ENV HOST=localhost

WORKDIR /app/express.service

RUN npm install

WORKDIR /app/flask.service

RUN apt-get update && \
apt-get -y install python3 python3-pip && \
pip3 install --upgrade pip &&\
pip3 install -U Flask flask-cors

WORKDIR /app

EXPOSE 3000

CMD env FLASK_APP=flask.service/app.py flask run & node express.service/bin/www